### PR TITLE
Update the README.md file with clearer installation instructions.

### PR DESCRIPTION
**Pull request by filipemsilv4**

### CODE REVIEW

**Review by micr0-dev — CHANGES_REQUESTED** [review]
Great improvements, however, the main target demographic of Lexido is Linux consider moving around the text a bit to prioritize Linux rather than macOs

**Comment by perdakovich** [comment]
I think that `/usr/local/bin/lexido` should be used for Linux too, instead of `/bin/lexido`
`/usr/bin` is managed by a package manager
and `/bin` is more of a system binaries directory

**Comment by filipemsilv4** [comment]
> I think that `/usr/local/bin/lexido` should be used for Linux too, instead of `/bin/lexido`
> `/usr/bin` is managed by a package manager
> and `/bin` is more of a system binaries directory

I wasn't aware of that; you're right, and it makes sense to change the directory from `/bin/lexido` to `/usr/local/bin/lexido`. Since lexido is not a critical program for system boot, the general convention is to install non-critical binaries in directories like `/usr/bin` or `/usr/local/bin`.

**Review by micr0-dev — APPROVED** [review]
Great changes, Approved

**Pull request merged**
